//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test12Noda2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// EnumASD.
    /// </summary>
    // *** Start programmer edit section *** (EnumASD CustomAttributes)

    // *** End programmer edit section *** (EnumASD CustomAttributes)
    public enum EnumASD
    {
    }
}
