//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test12Noda2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Test master.
    /// </summary>
    // *** Start programmer edit section *** (testMaster CustomAttributes)

    // *** End programmer edit section *** (testMaster CustomAttributes)
    [AutoAltered()]
    [Caption("Test master")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("testMasterE", new string[] {
            "countNum as \'Count num\'"})]
    [View("testMasterL", new string[] {
            "countNum as \'Count num\'"})]
    public class testMaster : ICSSoft.STORMNET.DataObject
    {
        
        private int fcountNum;
        
        // *** Start programmer edit section *** (testMaster CustomMembers)

        // *** End programmer edit section *** (testMaster CustomMembers)

        
        /// <summary>
        /// countNum.
        /// </summary>
        // *** Start programmer edit section *** (testMaster.countNum CustomAttributes)

        // *** End programmer edit section *** (testMaster.countNum CustomAttributes)
        public virtual int countNum
        {
            get
            {
                // *** Start programmer edit section *** (testMaster.countNum Get start)

                // *** End programmer edit section *** (testMaster.countNum Get start)
                int result = this.fcountNum;
                // *** Start programmer edit section *** (testMaster.countNum Get end)

                // *** End programmer edit section *** (testMaster.countNum Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (testMaster.countNum Set start)

                // *** End programmer edit section *** (testMaster.countNum Set start)
                this.fcountNum = value;
                // *** Start programmer edit section *** (testMaster.countNum Set end)

                // *** End programmer edit section *** (testMaster.countNum Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "testMasterE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View testMasterE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("testMasterE", typeof(IIS.Test12Noda2.testMaster));
                }
            }
            
            /// <summary>
            /// "testMasterL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View testMasterL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("testMasterL", typeof(IIS.Test12Noda2.testMaster));
                }
            }
        }
    }
}
