//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test12Noda2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Test main.
    /// </summary>
    // *** Start programmer edit section *** (testMain CustomAttributes)

    // *** End programmer edit section *** (testMain CustomAttributes)
    [AutoAltered()]
    [Caption("Test main")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("testMainE", new string[] {
            "asd as \'Asd\'",
            "asd2 as \'Asd2\'",
            "master as \'Master\'",
            "master.countNum as \'Count num\'"}, Hidden=new string[] {
            "master.countNum"})]
    [AssociatedDetailViewAttribute("testMainE", "detail", "testDetailE", true, "", "Detail", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("testMainE", "master", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "countNum")]
    [View("testMainL", new string[] {
            "asd as \'Asd\'",
            "asd2 as \'Asd2\'",
            "master.countNum as \'Count num\'"})]
    public class testMain : ICSSoft.STORMNET.DataObject
    {
        
        private int fasd;
        
        private string fasd2;
        
        private IIS.Test12Noda2.testMaster fmaster;
        
        private IIS.Test12Noda2.DetailArrayOftestDetail fdetail;
        
        // *** Start programmer edit section *** (testMain CustomMembers)

        // *** End programmer edit section *** (testMain CustomMembers)

        
        /// <summary>
        /// asd.
        /// </summary>
        // *** Start programmer edit section *** (testMain.asd CustomAttributes)

        // *** End programmer edit section *** (testMain.asd CustomAttributes)
        public virtual int asd
        {
            get
            {
                // *** Start programmer edit section *** (testMain.asd Get start)

                // *** End programmer edit section *** (testMain.asd Get start)
                int result = this.fasd;
                // *** Start programmer edit section *** (testMain.asd Get end)

                // *** End programmer edit section *** (testMain.asd Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (testMain.asd Set start)

                // *** End programmer edit section *** (testMain.asd Set start)
                this.fasd = value;
                // *** Start programmer edit section *** (testMain.asd Set end)

                // *** End programmer edit section *** (testMain.asd Set end)
            }
        }
        
        /// <summary>
        /// asd2.
        /// </summary>
        // *** Start programmer edit section *** (testMain.asd2 CustomAttributes)

        // *** End programmer edit section *** (testMain.asd2 CustomAttributes)
        [StrLen(255)]
        public virtual string asd2
        {
            get
            {
                // *** Start programmer edit section *** (testMain.asd2 Get start)

                // *** End programmer edit section *** (testMain.asd2 Get start)
                string result = this.fasd2;
                // *** Start programmer edit section *** (testMain.asd2 Get end)

                // *** End programmer edit section *** (testMain.asd2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (testMain.asd2 Set start)

                // *** End programmer edit section *** (testMain.asd2 Set start)
                this.fasd2 = value;
                // *** Start programmer edit section *** (testMain.asd2 Set end)

                // *** End programmer edit section *** (testMain.asd2 Set end)
            }
        }
        
        /// <summary>
        /// Test main.
        /// </summary>
        // *** Start programmer edit section *** (testMain.master CustomAttributes)

        // *** End programmer edit section *** (testMain.master CustomAttributes)
        [PropertyStorage(new string[] {
                "master"})]
        [NotNull()]
        public virtual IIS.Test12Noda2.testMaster master
        {
            get
            {
                // *** Start programmer edit section *** (testMain.master Get start)

                // *** End programmer edit section *** (testMain.master Get start)
                IIS.Test12Noda2.testMaster result = this.fmaster;
                // *** Start programmer edit section *** (testMain.master Get end)

                // *** End programmer edit section *** (testMain.master Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (testMain.master Set start)

                // *** End programmer edit section *** (testMain.master Set start)
                this.fmaster = value;
                // *** Start programmer edit section *** (testMain.master Set end)

                // *** End programmer edit section *** (testMain.master Set end)
            }
        }
        
        /// <summary>
        /// Test main.
        /// </summary>
        // *** Start programmer edit section *** (testMain.detail CustomAttributes)

        // *** End programmer edit section *** (testMain.detail CustomAttributes)
        public virtual IIS.Test12Noda2.DetailArrayOftestDetail detail
        {
            get
            {
                // *** Start programmer edit section *** (testMain.detail Get start)

                // *** End programmer edit section *** (testMain.detail Get start)
                if ((this.fdetail == null))
                {
                    this.fdetail = new IIS.Test12Noda2.DetailArrayOftestDetail(this);
                }
                IIS.Test12Noda2.DetailArrayOftestDetail result = this.fdetail;
                // *** Start programmer edit section *** (testMain.detail Get end)

                // *** End programmer edit section *** (testMain.detail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (testMain.detail Set start)

                // *** End programmer edit section *** (testMain.detail Set start)
                this.fdetail = value;
                // *** Start programmer edit section *** (testMain.detail Set end)

                // *** End programmer edit section *** (testMain.detail Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "testMainE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View testMainE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("testMainE", typeof(IIS.Test12Noda2.testMain));
                }
            }
            
            /// <summary>
            /// "testMainL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View testMainL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("testMainL", typeof(IIS.Test12Noda2.testMain));
                }
            }
        }
    }
}
